/*
 * File: msfcn_sendTorqueDataC.cpp
 *
 *
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is an S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_defines_Changes_BEGIN
  *        #define NAME 'replacement text' 
  *        %%% SFUNWIZ_defines_Changes_END
  *
  *   DO NOT change NAME--Change the 'replacement text' only.
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *  -------------------------------------------------------------------------
  * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
  *  ------------------------------------------------------------------------- 
 * Created: Wed Mar 25 11:19:00 2015
 * 
 *
 */

#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME msfcn_sendTorqueDataC
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NPARAMS              2
/* Parameter  1 */
#define PARAMETER_0_NAME      param_hostIP
#define PARAMETER_0_DTYPE     real_T
#define PARAMETER_0_COMPLEX   COMPLEX_NO
/* Parameter  2 */
#define PARAMETER_1_NAME      param_port
#define PARAMETER_1_DTYPE     real_T
#define PARAMETER_1_COMPLEX   COMPLEX_NO


#define NUM_INPUTS          2
/* Input Port  0 */
#define IN_PORT_0_NAME      torque
#define INPUT_0_WIDTH       7
#define INPUT_DIMS_0_COL    1
#define INPUT_0_DTYPE       real_T
#define INPUT_0_COMPLEX     COMPLEX_NO
#define IN_0_FRAME_BASED    FRAME_NO
#define IN_0_BUS_BASED      0
#define IN_0_BUS_NAME       
#define IN_0_DIMS           1-D
#define INPUT_0_FEEDTHROUGH 1
#define IN_0_ISSIGNED        0
#define IN_0_WORDLENGTH      8
#define IN_0_FIXPOINTSCALING 1
#define IN_0_FRACTIONLENGTH  9
#define IN_0_BIAS            0
#define IN_0_SLOPE           0.125
/* Input Port  1 */
#define IN_PORT_1_NAME      controllerType
#define INPUT_1_WIDTH       1
#define INPUT_DIMS_1_COL    1
#define INPUT_1_DTYPE       real_T
#define INPUT_1_COMPLEX     COMPLEX_NO
#define IN_1_FRAME_BASED    FRAME_NO
#define IN_1_BUS_BASED      0
#define IN_1_BUS_NAME       
#define IN_1_DIMS           1-D
#define INPUT_1_FEEDTHROUGH 1
#define IN_1_ISSIGNED        0
#define IN_1_WORDLENGTH      8
#define IN_1_FIXPOINTSCALING 1
#define IN_1_FRACTIONLENGTH  9
#define IN_1_BIAS            0
#define IN_1_SLOPE           0.125


#define NUM_OUTPUTS           0

#define SAMPLE_TIME_0        INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES      0
#define DISC_STATES_IC       [0]
#define NUM_CONT_STATES      0
#define CONT_STATES_IC       [0]

#define SFUNWIZ_GENERATE_TLC 1
#define SOURCEFILES "__SFB__"
#define PANELINDEX           6
#define USE_SIMSTRUCT        0
#define SHOW_COMPILE_STEPS   0                   
#define CREATE_DEBUG_MEXFILE 0
#define SAVE_CODE_ONLY       0
#define SFUNWIZ_REVISION     3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#include "mex.h"

#include <stdlib.h> 
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <netdb.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <arpa/inet.h>

#define PARAM_DEF0(S) ssGetSFcnParam(S, 0)
#define PARAM_DEF1(S) ssGetSFcnParam(S, 1)

#define SOCKFD        0
#define CONTROLSCHEME 1
  
void *get_in_addr(struct sockaddr *sa)
{
    if (sa->sa_family == AF_INET) {
        return &(((struct sockaddr_in*)sa)->sin_addr);
    }

    return &(((struct sockaddr_in6*)sa)->sin6_addr);
}

/*====================*
 * S-function methods *
 *====================*/

#define MDL_CHECK_PARAMETERS
#if defined(MDL_CHECK_PARAMETERS) && defined(MATLAB_MEX_FILE)
/* Function: mdlCheckParameters =============================================
* Abstract:
*    Validate our parameters to verify they are okay.
*/
static void mdlCheckParameters(SimStruct *S)
{
    int paramIndex  = 0;
    bool invalidParam = false;
    /* All parameters must match the S-function Builder Dialog */

    const mxArray *pVal0 = ssGetSFcnParam(S,0);   
    const mxArray *pVal1 = ssGetSFcnParam(S,1);
    
    if (!mxIsChar(pVal0)) {
        invalidParam = true;
        paramIndex = 0;
        goto EXIT_POINT;
    }

    if (!mxIsChar(pVal1)) {
        invalidParam = true;
        paramIndex = 1;
        goto EXIT_POINT;
    }

    EXIT_POINT:
    if (invalidParam) {
        char parameterErrorMsg[1024];
        sprintf(parameterErrorMsg, "The data type of parameter %d is not valid. "
              "Please input char array parameters (\'host\', \'port number\')" , paramIndex + 1);
        ssSetErrorStatus(S,parameterErrorMsg);
    }
    return;
}
#endif

/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{
    DECL_AND_INIT_DIMSINFO(inputDimsInfo);
    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);
    
    #if defined(MATLAB_MEX_FILE)
	if (ssGetNumSFcnParams(S) == ssGetSFcnParamsCount(S)) {
        mdlCheckParameters(S);
        if (ssGetErrorStatus(S) != NULL) {
            return;
        }
    } else {
        return; /* Parameter mismatch will be reported by Simulink */
    }
    #endif

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);

    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;
    /* Input Port 0 */
    ssSetInputPortWidth(S, 0, INPUT_0_WIDTH);
    ssSetInputPortDataType(S, 0, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 0, 1); /*direct input signal access*/
    /* Input Port 1 */
    ssSetInputPortWidth(S, 1, INPUT_1_WIDTH);
    ssSetInputPortDataType(S, 1, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 1, 1); /*direct input signal access*/

    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    
    ssSetNumSampleTimes(S, 1);
    ssSetNumIWork(S, 2); //using the integer work vector instead of global variables!!!!! Holds sockfd and controller scheme
    ssSetNumRWork(S, 0);
    ssSetNumPWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                     SS_OPTION_USE_TLC_WITH_ACCELERATOR | 
		     SS_OPTION_WORKS_WITH_CODE_REUSE));
    
    mexPrintf("sendTorqueData - Initialized!\n");
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_START  /* Change to #undef to remove function */
#if defined(MDL_START) 
  /* Function: mdlStart =======================================================
   * Abstract:
   *    This function is called once at start of model execution. If you
   *    have states that should be initialized once, this is the place
   *    to do it.
   */
static void mdlStart(SimStruct *S)
{
    /* Set up socket client (daVinci C++ streams) */
    struct addrinfo hints, *servinfo, *p;
    int rv, sockfd;
    char s[INET6_ADDRSTRLEN];
    
    memset(&hints, 0, sizeof hints);
    hints.ai_family   = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;
        
    const int LENGTH = 50; 
    char_T tcpip_hostIP[2];
    char_T tcpip_portNum[LENGTH];
    
    mxGetString(ssGetSFcnParam(S, 0), tcpip_hostIP, LENGTH);
    mxGetString(ssGetSFcnParam(S, 1), tcpip_portNum, LENGTH);
        
    if ((rv = getaddrinfo(tcpip_hostIP, tcpip_portNum, &hints, &servinfo)) != 0) 
    {
        mexPrintf("getaddrinfo: %s\n", gai_strerror(rv));
        return;
    }
    
    /* loop through all the results and connect to the first we can */
    for(p = servinfo; p != NULL; p = p->ai_next) 
    {
        if ((sockfd = socket(p->ai_family, p->ai_socktype, p->ai_protocol)) == -1) 
        {
            mexPrintf("Torque client: socket\n");
            continue;
        }
        if (connect(sockfd, p->ai_addr, p->ai_addrlen) == -1) 
        {
            close(sockfd);
            mexPrintf("Torque client   : connect on %s port %s (sockfd = %i)\n", tcpip_hostIP, tcpip_portNum, sockfd);
            continue;
        }
        break;
    }
    
    if (p == NULL) 
    {
        mexPrintf("Torque client: failed to connect\n");
        return;
    }
   
    
    inet_ntop(p->ai_family, get_in_addr((struct sockaddr *)p->ai_addr), s, sizeof s);
    mexPrintf("Torque client   : connecting to %s on port %s (sockfd = %i)\n", s, tcpip_portNum, sockfd);
    freeaddrinfo(servinfo); // all done with this structure  
        
    //Initialize work vector 
    int *internalVars = ssGetIWork(S); /* integer typed*/
    internalVars[SOCKFD]        = sockfd;
    internalVars[CONTROLSCHEME] = -1;
    
}
#endif /*  MDL_START */

#define MDL_SET_INPUT_PORT_DATA_TYPE
static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetInputPortDataType(S, 0, dType);
}
#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType( S, 0, SS_DOUBLE);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

/* Function: mdlOutputs =======================================================
 *
*/
static void mdlOutputs(SimStruct *S, int_T tid)
{
    //get sockFd and controllerScheme
    int_T *internalVars = ssGetIWork(S); /* integer typed*/    
    int controlScheme = internalVars[CONTROLSCHEME];
    int sockfd        = internalVars[SOCKFD];
   
    if(sockfd == 0) //failed to initialize
        return;
    
    const real_T   *torque          = (const real_T*) ssGetInputPortSignal(S,0);
    
    if(controlScheme == -1) { //first run
        const real_T   *controllerType  = (const real_T*) ssGetInputPortSignal(S,1);
        internalVars[CONTROLSCHEME]     = (int)controllerType[0]; //update work vector
        controlScheme                   = internalVars[CONTROLSCHEME]; //reset this value
    }

    int numbytes, MAXDATASIZE;
    if(controlScheme == 0) //joint level controller    
        MAXDATASIZE = 70;
    else if(controlScheme == 1) //cartesian controller
        MAXDATASIZE = 55;
    
    char buf[MAXDATASIZE];
    
    int size = -1;
    
    if(controlScheme == 0) { //joint level controller    
        size = sprintf(buf, "%08.4f, %08.4f, %08.4f, %08.4f, %08.4f, %08.4f, %08.4f", torque[0], torque[1], torque[2], torque[3], torque[4], torque[5], torque[6]);    
    }
    else if(controlScheme == 1) { //cartesian controller    
        size = sprintf(buf, "%08.4f,%08.4f,%08.4f,%08.4f,%08.4f,%08.4f", torque[0], torque[1], torque[2], torque[3], torque[4], torque[5]);
    }
      
    if ((numbytes = send(sockfd, buf, MAXDATASIZE-1, 0)) == -1) {
        //mexPrintf("Send Failed\n");
    }        
}



/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
    //get sockFd and controllerScheme
    int_T *internalVars = ssGetIWork(S); /* integer typed*/    
    int controlScheme = internalVars[CONTROLSCHEME];
    int sockfd        = internalVars[SOCKFD];
    
    int numbytes;
    int MAXDATASIZE = 30;
    char buf[MAXDATASIZE];
    
    int size = -1;
    if(controlScheme == 0) //joint level controller  
        size = sprintf(buf, "%i, %i, %i, %i, %i, %i, %i", -1,-1,-1,-1,-1,-1,-1);
    else if(controlScheme == 1) //cartesian controller 
        size = sprintf(buf, "%i, %i, %i, %i, %i, %i", -1,-1,-1,-1,-1,-1);        
    
    if ((numbytes = send(sockfd, buf, MAXDATASIZE-1, 0)) == -1) {
        mexPrintf("Send Failed\n");
    }
    close(sockfd);
    mexPrintf("Closing torque socket (sockfd = %i)\n", sockfd);
}
#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif


